### ISSUE TITLE
Agora 3.0.1.1 updates

### ISSUE THREAD

**Issue by softsan** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#13]
Hi,

I see Agora released native 3.0.1.1 SDK for iOS and Android on 18th June 2020.

https://docs.agora.io/en/Video/release_ios_video?platform=iOS#v3011
https://docs.agora.io/en/Video/release_android_video?platform=Android#v3011

So is there any chance to update the same for Xamarin nuget package.
Thanks.

**Comment by sbokatuk** [comment]
Hello, nuget packages for 3.0.1.1 available. if you have issues with appstore build on ios - use latest beta package - it not contain emulator links
