### ISSUE TITLE
Local view is not showing when Remote view appears.

### ISSUE THREAD

**Issue by AmitBishnoi246** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#21]
Hi there,

I am working in Xamarin forms for one to one call using agora. Everything is working fine except whenever the call is connected and remote view appears the local view gets removed or overlapped by it. We are using grid view by which local view is displayed above remote view in the ratio of 1:6. When we start call local view is working fine but when another user joins call remote view appears and disable local view. And when we tap on the button to change mode of local view it reappears and if we change mode of remote view the local view disappears again. 
 
any idea how i can achieve video calling view like WhatsApp . Thanks

**Comment by alexsorokoletov** [comment]
Hi @AmitBishnoi246!
Thanks for the issue report.

I guess this document might be helpful https://docs.agora.io/en/Quickstart%20Guide/communication_android_video-1#setting-the-local-video-view

Specifically look into `surfaceView.setZOrderMediaOverlay`. What you described is Android issue (not related to Agora per se) when a surface view overlays another surface view.

Hope this helps!

**Comment by AmitBishnoi246** [comment]
`surfaceView.setZOrderMediaOverlay` is true for both Local and Remote View but now i change remote `surfaceView.setZOrderMediaOverlay` to `false` and now it works fine. You made my day. Thanks @alexsorokoletov .
