### ISSUE TITLE
No Audio when answering from a killed state

### ISSUE THREAD

**Issue by yonkahlon** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#22]
Hi

I'm using Xamarin.Agora.Full.iOS v 3.2.1 with CallKit and PushKit so that users can receive calls when the app is in a killed state.

Issue: There is no audio when I answer the call from a killed state. We only do 1:1 video calls. Video works fine every time. I've tried to disableAudio then enableAudio on both sides, I've made sure both sides are unmuted, etc.

I can see from the End-To-End Details in the Agora Analytics for that particular call that there is no audio transfer. Agora doesn't throw any errors, and I've googled the issue but can't find anything.

I'm not sure if this is a bug or if I'm doing something wrong. Any advice on how to get more information would be very helpful!

**Comment by alexsorokoletov** [comment]
Hi @yonkahlon!
This does not look right to me, it should be working all right. That also means that this issue can be fixed 🙌 

You could check the following things:
1. Reproduce the problem and use Agora web demo tools to join that same channel and see if a) web can hear calling side or receiving side b) if calling or receiving side can hear web. 
Any discrepancy here might indicate where you are losing sound if it's in the Agora SDK setup.

2. Double check your Agora Logs (on devices) - see if you have any AVAudioSession warnings or Agora errors on any of the sides

**Comment by yonkahlon** [comment]
Hi @alexsorokoletov 

Thanks for the information!

I tried with the [Agora 1-to-1 web demo](https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/). There is no audio when calling from background state, but there is audio when calling from foreground state. I was using my phone for this and I couldn't transmit audio or video - I couldn't figure out why... This suggests that we're not transmitting audio.

I can't get the physical log files. I've tried the following, but there are no log files (I am able to create files in this dir from the app):
```
            _agoraEngine.SetLogFile(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments));
            _agoraEngine.SetLogFilter((uint) LogFilter.Debug);
            _agoraEngine.SetLogFileSize(1024 * 1024);
```

I haven't been able to enable the sandbox so that the logs save to the default dir. I'll give that a go tomorrow :-)

**Comment by yonkahlon** [comment]
I figured it out :-)

Firstly - to get logs working you need to specify a file name, not just a directory:
```
            var documents = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            var filename = Path.Combine(documents, "AgoraLogs.txt");

            _agoraEngine.SetLogFile(filename);
            _agoraEngine.SetLogFilter((uint) LogFilter.Debug);
            _agoraEngine.SetLogFileSize(1024 * 1024);
```

In the logs I found a warning saying that Agora couldn't activate the audio session.

A bit more digging and I found [this issue](https://github.com/twilio/twilio-video-ios/issues/8). A Twilio user was having the same problem, but it wasn't related to Twilio - you need to activate the audio session before you report the call to CallKit.

Thanks for pointing me in the right direction!

**Comment by alexsorokoletov** [comment]
Happy for you @yonkahlon and glad you were able to find the root cause and fix it 👍
