### ISSUE TITLE
Linker Error when Building for iOS

### ISSUE THREAD

**Issue by carbon-paulc** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#3]
Hi,
I'm trying to use this nuget package (Xamarin.Agora.Full.Forms) in a .NET Standard Xamarin.Forms project.

Everything works on Android okay, however, when I try to build for the AppStore I'm getting some Linker errors.

Any help would be appreciated.

Thanks in advance,
Paul.
5>  Undefined symbols for architecture armv7s:
5>    "_AgoraVideoBitrateCompatible", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoBitrateCompatible)
5>    "_AgoraVideoBitrateStandard", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoBitrateStandard)
5>    "_AgoraVideoDimension120x120", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension120x120)
5>    "_AgoraVideoDimension1280x720", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension1280x720)
5>    "_AgoraVideoDimension160x120", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension160x120)
5>    "_AgoraVideoDimension180x180", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension180x180)
5>    "_AgoraVideoDimension1920x1080", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension1920x1080)
5>    "_AgoraVideoDimension240x180", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension240x180)
5>    "_AgoraVideoDimension240x240", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension240x240)
5>    "_AgoraVideoDimension2540x1440", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension2540x1440)
5>    "_AgoraVideoDimension320x180", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension320x180)
5>    "_AgoraVideoDimension320x240", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension320x240)
5>    "_AgoraVideoDimension360x360", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension360x360)
5>    "_AgoraVideoDimension3840x2160", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension3840x2160)
5>    "_AgoraVideoDimension424x240", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension424x240)
5>    "_AgoraVideoDimension480x360", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension480x360)
5>    "_AgoraVideoDimension480x480", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension480x480)
5>    "_AgoraVideoDimension640x360", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension640x360)
5>    "_AgoraVideoDimension640x480", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension640x480)
5>    "_AgoraVideoDimension840x480", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension840x480)
5>    "_AgoraVideoDimension960x720", referenced from:
5>       -u command line option
5>       (maybe you meant: _Xamarin_Agora_Full_iOS_DT_Xamarin_Agora_Constants_get_AgoraVideoDimension960x720)
5>    "_OBJC_CLASS_$_AgoraChannelStats", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraImage", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraLiveInjectStreamConfig", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraLiveTranscoding", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraLiveTranscodingUser", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraPublisherConfiguration", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcAudioVolumeInfo", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcDefaultCamera", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcDefaultRenderer", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcEngineKit", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcLocalVideoStats", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcRemoteVideoStats", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcVideoCanvas", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcVideoCompositingLayout", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraRtcVideoCompositingRegion", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraVideoEncoderConfiguration", referenced from:
5>        objc-class-ref in registrar.o
5>    "_OBJC_CLASS_$_AgoraVideoFrame", referenced from:
5>        objc-class-ref in registrar.o
5>       (maybe you meant: _OBJC_CLASS_$_AgoraVideoFrameConsumer)
5>  ld: symbol(s) not found for architecture armv7s
5>  clang: error: linker command failed with exit code 1 (use -v to see invocation)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5209: Native linking error: warning: ignoring file /Users/pcharlton/Library/Caches/Xamarin/mtbs/builds/Kingdom.MyCare.iOS/245ff3320e81ecbf962604d451a97f88/obj/iPhone/AppStore/mtouch-cache/AgoraRtcCryptoLoader.framework/AgoraRtcCryptoLoader, missing required architecture armv7s in file /Users/pcharlton/Library/Caches/Xamarin/mtbs/builds/Kingdom.MyCare.iOS/245ff3320e81ecbf962604d451a97f88/obj/iPhone/AppStore/mtouch-cache/AgoraRtcCryptoLoader.framework/AgoraRtcCryptoLoader (4 slices)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5209: Native linking error: warning: ignoring file /Users/pcharlton/Library/Caches/Xamarin/mtbs/builds/Kingdom.MyCare.iOS/245ff3320e81ecbf962604d451a97f88/obj/iPhone/AppStore/mtouch-cache/AgoraRtcEngineKit.framework/AgoraRtcEngineKit, missing required architecture armv7s in file /Users/pcharlton/Library/Caches/Xamarin/mtbs/builds/Kingdom.MyCare.iOS/245ff3320e81ecbf962604d451a97f88/obj/iPhone/AppStore/mtouch-cache/AgoraRtcEngineKit.framework/AgoraRtcEngineKit (4 slices)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoBitrateCompatible. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoBitrateCompatible. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoBitrateStandard. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoBitrateStandard. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension120x120. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension120x120. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension1280x720. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension1280x720. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension160x120. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension160x120. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension180x180. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension180x180. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension1920x1080. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension1920x1080. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension240x180. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension240x180. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension240x240. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension240x240. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension2540x1440. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension2540x1440. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension320x180. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension320x180. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension320x240. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension320x240. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension360x360. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension360x360. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension3840x2160. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension3840x2160. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension424x240. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension424x240. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension480x360. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension480x360. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension480x480. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension480x480. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension640x360. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension640x360. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension640x480. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension640x480. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension840x480. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension840x480. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5214: Native linking failed, undefined symbol: _AgoraVideoDimension960x720. This symbol was referenced by the managed member DT.Xamarin.Agora.Constants.AgoraVideoDimension960x720. Please verify that all the necessary frameworks have been referenced and native libraries linked.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraChannelStats. The symbol '_OBJC_CLASS_$_AgoraChannelStats' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraImage. The symbol '_OBJC_CLASS_$_AgoraImage' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraLiveInjectStreamConfig. The symbol '_OBJC_CLASS_$_AgoraLiveInjectStreamConfig' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraLiveTranscoding. The symbol '_OBJC_CLASS_$_AgoraLiveTranscoding' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraLiveTranscodingUser. The symbol '_OBJC_CLASS_$_AgoraLiveTranscodingUser' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraPublisherConfiguration. The symbol '_OBJC_CLASS_$_AgoraPublisherConfiguration' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcAudioVolumeInfo. The symbol '_OBJC_CLASS_$_AgoraRtcAudioVolumeInfo' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcDefaultCamera. The symbol '_OBJC_CLASS_$_AgoraRtcDefaultCamera' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcDefaultRenderer. The symbol '_OBJC_CLASS_$_AgoraRtcDefaultRenderer' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcEngineKit. The symbol '_OBJC_CLASS_$_AgoraRtcEngineKit' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcLocalVideoStats. The symbol '_OBJC_CLASS_$_AgoraRtcLocalVideoStats' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcRemoteVideoStats. The symbol '_OBJC_CLASS_$_AgoraRtcRemoteVideoStats' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcVideoCanvas. The symbol '_OBJC_CLASS_$_AgoraRtcVideoCanvas' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcVideoCompositingLayout. The symbol '_OBJC_CLASS_$_AgoraRtcVideoCompositingLayout' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraRtcVideoCompositingRegion. The symbol '_OBJC_CLASS_$_AgoraRtcVideoCompositingRegion' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraVideoEncoderConfiguration. The symbol '_OBJC_CLASS_$_AgoraVideoEncoderConfiguration' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5211: Native linking failed, undefined Objective-C class: AgoraVideoFrame. The symbol '_OBJC_CLASS_$_AgoraVideoFrame' could not be found in any of the libraries or frameworks linked with your application.
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT5202: Native linking failed. Please review the build log.

**Comment by alexsorokoletov** [comment]
@carbon-paulc Paul, I think `armv7s` is not supported by Agora SDK which (if I recall correctly) only supports 64bit apps now (same as many other current iOS SDKs).
