### ISSUE TITLE
Can't Diagnose Connection Errors

### ISSUE THREAD

**Issue by jlchavez** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#30]
No State is changed when connection has failed from "onConnectionStateChanged", no Error is received from "onError", no error found on Device Logs in Andriod Emulator, no exceptions could be capture on Xamarin side to send to Microsoft AppCenter, even providing a token from Agora Console fails and the app crashes. Couldn't get to test on iOS since the project requires both platforms. 

I undestand some, most or all of this things are from Agora Java/C++, not from this SDK I've developed the solution with Vidyo, now with Agora, and will swtich to OpenTok to see if I can rescue the application or cancel the project since each one has a problem with Xamarin Forms and it would take to much time to adapt the UI of all the features to each platform.

**Comment by sbokatuk** [comment]
are you about Forms packages? if yes - that thread is only about native  nugets, forms support you can find here https://github.com/DreamTeamMobile/Xamarin.Agora.Samples

we working there on updates to Forms versions to have events and all functionality mirrored from native
