### ISSUE TITLE
Not able to set geo fencing in Agora in Xamarin forms

### ISSUE THREAD

**Issue by vvdPrasadReddy** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#34]
I'm trying to enable geo fencing in our Xamarin forms App. but not able to include this code 
        RtcEngineConfig config = new RtcEngineConfig();
        config.mAppId = appId;
        config.mContext = mContext;
        config.mEventHandler = mEngineEventHandler.mRtcEventHandler;
        config.mAreaCode = AREA_CODE_EU;
        mRtcEngine = RtcEngine.create(config);
I think Agora-RTC-SDK for Xamarin did not exposed the geo fencing configuration. 
Can anyone give me any suggestions to achieve this? 
thanks in advance

**Comment by sbokatuk** [comment]
@vvdPrasadReddy native SDK is not related to Forms version, please post Forms issues here https://github.com/DreamTeamMobile/Xamarin.Agora.Samples

**Comment by sbokatuk** [comment]
and yes, Forms now updating, in current version it missing Config you mentioned

**Comment by vvdPrasadReddy** [comment]
ok thanks @sbokatuk
