### ISSUE TITLE
Xamarin.Forms Broadcasting 

### ISSUE THREAD

**Issue by stephenpaulraj** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#4]
This nuget package which says Agora.Full is working fine with One to One. How do i add broadcasting function to my app. Before invoking StartSession the setChannelProfile()
has to be set to LiveBroadcasting with ClientRole as Host or Audience. IAgoraService or other classes has no context pointing out.

Can you provide me a solution. If possible with a Sample.

**Comment by alexsorokoletov** [comment]
@stephenpaulraj the Xamarin.Forms Agora SDK is covering only simple use cases. To fully use the power of Agora iOS/Android SDK with Forms, you will need to create your own classes similar to the way this SDK is structured. 
Or get enough thumbs up on this thread to prioritize the improvement of this SDK.
