### ISSUE TITLE
Android Stream Layering Issue

### ISSUE THREAD

**Issue by NVentimiglia** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#6]
In our design we have multiple video streams. One video stream is "the main presenter" and rests in the background. The other streams are smaller and rest inside a list view on-top. Many times when we have multiple streams (3+) the smaller top-level streams "disappear". 

They still exist and are trappable, but they are not being rendered. It seems they are rendered behind the main background stream. When we tap, this causes a re-sort of the layers (switching main presenter). At this point they might appear.

How can we solve this, it is android only. How can we control the Z-index of these streams?

**Comment by Lionelfelix** [comment]
Hola amigo como resolviste el problema, me pasa lo mismo
