### ISSUE TITLE
RenewToken not working on android or iOS

### ISSUE THREAD

**Issue by NVentimiglia** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#7]
Attempting to implement security. The RenewToken method does not work on iOS or Android.

I modified the API so I could pass the token into the service implementation here.
https://github.com/AgoraIO-Community/Agora-RTC-SDK-for-Xamarin/blob/master/Xamarin.Agora.Forms/Xamarin.Agora.Full.Forms.Android/AgoraServiceImplementation.cs#L147

Once passed, I cache the token and sign in with it. This works fine.

I also handle the OnTokenPrivilegeWillExpire event from the engine class.
https://github.com/AgoraIO-Community/Agora-RTC-SDK-for-Xamarin/blob/master/Xamarin.Agora.Forms/Xamarin.Agora.Full.Forms.Android/AgoraServiceImplementation.cs#L688

My implementation looks like this

 public void OnTokenPrivilegeWillExpire(string token)
        {
            var r = _agoraEngine.RenewToken(token);
            System.Console.WriteLine("AgoraVideoService.HandleTokenRenew " + r);
        }

The result is 0 (success). But, shortly after an error is raised letting me know the token has expired.

**Comment by alexsorokoletov** [comment]
Hi @NVentimiglia!

This is interesting, that both iOS and Android does not work.

According to the docs https://docs.agora.io/en/Agora%20Platform/token

>A token (or a temporary token) expires after a certain period of time. When the SDK notifies the client that **the token is about to expire or has expired** by the onTokenPrivilegeWillExpire or onTokenExpired callbacks, you need to generate a new token and call the renewToken method.

Is it possible that you get this event when the token is expired?


Also, the docs mention somewhat different ways to handle renewal:
iOS:
>The app should call this method to get the token. Failure to do so results in the SDK disconnecting from the server.

Android:
>The app should retrieve a new token from the server and call this method to renew it. Failure to do so results in the SDK disconnecting from the server.


[iOS](https://docs.agora.io/en/Agora%20Platform/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/renewToken:)

[Android](https://docs.agora.io/en/Agora%20Platform/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#af1428905e5778a9ca209f64592b5bf80)

If you have a sample that works on iOS Swift or Android Java, could you please post it here so we can find out why Xamarin SDK does not work?

**Comment by NVentimiglia** [comment]
> Is it possible that you get this event when the token is expired?

The will expire event is raised, and I do call the renew token method. 

I have also tried manually emulating the will expire method with my own timeout / delay method (in a loop). This method also fails.

When we call this method it returns 0, success.

> The app should retrieve a new token from the server and call this method to renew it.

This is different than the other sdks, but ok, Ill ask agora.

**Comment by alexsorokoletov** [comment]
I think it will be faster if you just take a Swift or Android Java example and try with your token and app id. 

Once we know the problem is with the Xamarin layer we can fix it rather fast.

**Comment by sbokatuk** [comment]
checked, got new token, send in renew token method this token - all is working on 3.3.1
